// SubliStudio CEP - Document Operations
#target photoshop

function openDocument(path){try{var file=new File(path);if(!file.exists){return JSON.stringify({success:false,error:"File not found: "+path})}var doc=app.open(file);return JSON.stringify({success:true,message:"Document opened",docName:doc.name,docPath:doc.fullName.fsName,width:doc.width.as("px"),height:doc.height.as("px"),resolution:doc.resolution.as("px/in"),colorMode:doc.mode.toString(),layerCount:doc.layers.length})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function closeDocument(save){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;if(save){doc.save();doc.close();return JSON.stringify({success:true,message:"Document saved and closed"})}else{doc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:true,message:"Document closed without saving"})}}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function createDocument(widthCm,heightCm,dpi,name,colorMode){try{var width=UnitValue(widthCm,"cm");var height=UnitValue(heightCm,"cm");var resolution=UnitValue(dpi,"px/in");var mode=NewDocumentMode.RGB;if(colorMode==="CMYK")mode=NewDocumentMode.CMYK;else if(colorMode==="Grayscale")mode=NewDocumentMode.GRAYSCALE;else if(colorMode==="Bitmap")mode=NewDocumentMode.BITMAP;else if(colorMode==="Lab")mode=NewDocumentMode.LAB;var doc=app.documents.add(width,height,resolution,name,mode,DocumentFill.TRANSPARENT);return JSON.stringify({success:true,message:"Document created",docName:doc.name,width:doc.width.as("px"),height:doc.height.as("px"),resolution:doc.resolution.as("px/in"),colorMode:doc.mode.toString()})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getDocumentInfo(){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;return JSON.stringify({success:true,docName:doc.name,docPath:doc.fullName?doc.fullName.fsName:"",width:doc.width.as("px"),height:doc.height.as("px"),widthCm:doc.width.as("cm"),heightCm:doc.height.as("cm"),resolution:doc.resolution.as("px/in"),colorMode:doc.mode.toString(),layerCount:doc.layers.length,hasBackground:doc.backgroundLayer!==null,bitsPerChannel:doc.bitsPerChannel})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function saveDocument(path,format){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;if(!path){doc.save();return JSON.stringify({success:true,message:"Document saved"})}var file=new File(path);var saveOptions;if(format==="PSD"){saveOptions=new PhotoshopSaveOptions();saveOptions.alphaChannels=true;saveOptions.layers=true;saveOptions.embedColorProfile=true}else if(format==="JPEG"){saveOptions=new JPEGSaveOptions();saveOptions.quality=12;saveOptions.embedColorProfile=true}else if(format==="PNG"){saveOptions=new PNGSaveOptions();saveOptions.compression=1}else if(format==="TIFF"){saveOptions=new TiffSaveOptions();saveOptions.LZW=true}else if(format==="PDF"){saveOptions=new PDFSaveOptions()}else{return JSON.stringify({success:false,error:"Unknown format: "+format})}doc.saveAs(file,saveOptions,true,Extension.LOWERCASE);return JSON.stringify({success:true,message:"Document saved as "+format,path:path})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}
