// SubliStudio CEP - Effects & Filters
#target photoshop

function applyCircularMask(layerName,x,y,radius){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var bounds=[UnitValue(x-radius,"px"),UnitValue(y-radius,"px"),UnitValue(x+radius,"px"),UnitValue(y+radius,"px")];doc.selection.select(bounds,SelectionType.REPLACE,0,false);doc.selection.invert();doc.selection.clear();doc.selection.deselect();return JSON.stringify({success:true,message:"Circular mask applied",layerName:layerName,x:x,y:y,radius:radius})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function applyGaussianBlur(layerName,radius){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var idGaussianBlur=stringIDToTypeID("Gaussian Blur");var desc=new ActionDescriptor();var idRadius=charIDToTypeID("Rad ");desc.putUnitDouble(idRadius,charIDToTypeID("#Pxl"),radius);executeAction(idGaussianBlur,desc,DialogModes.NO);return JSON.stringify({success:true,message:"Gaussian blur applied",layerName:layerName,radius:radius})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function applyLayerStyle(layerName,styleType,params){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(styleType==="dropShadow"){layer.effect.dropShadow=true;if(params.distance)layer.effects.dropShadow.distance=params.distance;if(params.size)layer.effects.dropShadow.size=params.size;if(params.opacity)layer.effects.dropShadow.opacity=params.opacity}else if(styleType==="bevel"){layer.effect.bevelEmboss=true;if(params.size)layer.effects.bevelEmboss.size=params.size;if(params.depth)layer.effects.bevelEmboss.depth=params.depth}else if(styleType==="outerGlow"){layer.effect.outerGlow=true;if(params.size)layer.effects.outerGlow.size=params.size;if(params.opacity)layer.effects.outerGlow.opacity=params.opacity}return JSON.stringify({success:true,message:"Layer style applied",layerName:layerName,styleType:styleType})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function mirrorLayer(layerName,axis){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;if(axis==="horizontal"){doc.flipCanvasHorizontal()}else if(axis==="vertical"){doc.flipCanvasVertical()}else{return JSON.stringify({success:false,error:"Invalid axis: "+axis})}return JSON.stringify({success:true,message:"Layer mirrored",layerName:layerName,axis:axis})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function applyColorOverlay(layerName,r,g,b,opacity){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}layer.effect.colorOverlay=true;layer.effects.colorOverlay.color.rgb.red=r;layer.effects.colorOverlay.color.rgb.green=g;layer.effects.colorOverlay.color.rgb.blue=b;layer.effects.colorOverlay.opacity=opacity;return JSON.stringify({success:true,message:"Color overlay applied",layerName:layerName,color:{r:r,g:g,b:b},opacity:opacity})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}
