// SubliStudio CEP - Export Operations
#target photoshop

function flattenAndExport(format,path,options){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var file=new File(path);var dupDoc=doc.duplicate();dupDoc.flatten();var saveOptions;if(format==="PNG"){saveOptions=new PNGSaveOptions();saveOptions.compression=options&&options.compression?options.compression:1}else if(format==="JPEG"){saveOptions=new JPEGSaveOptions();saveOptions.quality=options&&options.quality?options.quality:12;saveOptions.embedColorProfile=true}else if(format==="TIFF"){saveOptions=new TiffSaveOptions();saveOptions.LZW=options&&options.compression?options.compression:true}else if(format==="PDF"){saveOptions=new PDFSaveOptions()}else{dupDoc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:false,error:"Unknown format: "+format})}dupDoc.saveAs(file,saveOptions,true,Extension.LOWERCASE);dupDoc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:true,message:"Document flattened and exported",format:format,path:path,width:doc.width.as("px"),height:doc.height.as("px")})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function exportLayer(layerName,path,format){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}var originalVisibility=[];for(var i=0;i<doc.layers.length;i++){originalVisibility.push(doc.layers[i].visible);doc.layers[i].visible=false}layer.visible=true;var file=new File(path);var saveOptions;if(format==="PNG"){saveOptions=new PNGSaveOptions()}else if(format==="JPEG"){saveOptions=new JPEGSaveOptions();saveOptions.quality=12}else if(format==="TIFF"){saveOptions=new TiffSaveOptions();saveOptions.LZW=true}else{saveOptions=new PNGSaveOptions()}doc.saveAs(file,saveOptions,true,Extension.LOWERCASE);for(var i=0;i<doc.layers.length;i++){doc.layers[i].visible=originalVisibility[i]}return JSON.stringify({success:true,message:"Layer exported",layerName:layerName,path:path,format:format})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function exportPreview(path,maxWidth){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var dupDoc=doc.duplicate();dupDoc.flatten();var currentWidth=dupDoc.width.as("px");if(currentWidth>maxWidth){var scale=(maxWidth/currentWidth)*100;dupDoc.resizeImage(UnitValue(scale,"%"),null,null,ResampleMethod.BICUBIC)}var file=new File(path);var saveOptions=new JPEGSaveOptions();saveOptions.quality=8;saveOptions.embedColorProfile=false;dupDoc.saveAs(file,saveOptions,true,Extension.LOWERCASE);dupDoc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:true,message:"Preview exported",path:path,width:dupDoc.width.as("px"),height:dupDoc.height.as("px")})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function createPrintSheet(widthCm,heightCm,dpi,designs){try{var sheet=app.documents.add(UnitValue(widthCm,"cm"),UnitValue(heightCm,"cm"),UnitValue(dpi,"px/in"),"Print Sheet",NewDocumentMode.RGB,DocumentFill.WHITE);for(var i=0;i<designs.length;i++){var design=designs[i];var file=new File(design.path);if(file.exists){var placedLayer=sheet.placedLayer(file);var bounds=placedLayer.bounds;var deltaX=UnitValue(design.x,"px")-bounds[0];var deltaY=UnitValue(design.y,"px")-bounds[1];placedLayer.translate(deltaX,deltaY);if(design.mirror){sheet.activeLayer=placedLayer;var idflip=stringIDToTypeID("flip");var desc=new ActionDescriptor();var idHrzn=charIDToTypeID("Hrzn");desc.putUnitDouble(idHrzn,charIDToTypeID("#Pxl"),0);executeAction(idflip,desc,DialogModes.NO)}}}return JSON.stringify({success:true,message:"Print sheet created",designCount:designs.length,docName:sheet.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}
