// SubliStudio CEP - ExtendScript Host Functions
#target photoshop

function getPhotoshopInfo(){try{var info={version:app.version,appName:app.name,hasDoc:false,docName:"",docWidth:0,docHeight:0,docResolution:0,colorMode:""};if(app.documents.length>0){var doc=app.activeDocument;info.hasDoc=true;info.docName=doc.name;info.docWidth=doc.width.as("cm");info.docHeight=doc.height.as("cm");info.docResolution=doc.resolution.as("px/in");switch(doc.mode){case DocumentMode.RGB:info.colorMode="RGB";break;case DocumentMode.CMYK:info.colorMode="CMYK";break;case DocumentMode.GRAYSCALE:info.colorMode="Grayscale";break;case DocumentMode.BITMAP:info.colorMode="Bitmap";break;case DocumentMode.LAB:info.colorMode="Lab";break;default:info.colorMode="Unknown"}}return JSON.stringify(info)}catch(e){return JSON.stringify({error:true,message:e.toString()})}}

function pingPhotoshop(){try{return JSON.stringify({success:true,version:app.version,message:"Photoshop is responding"})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function createTestDocument(){try{var doc=app.documents.add(UnitValue(21,"cm"),UnitValue(29.7,"cm"),300,"SubliStudio Test",NewDocumentMode.RGB);return JSON.stringify({success:true,message:"Document created: "+doc.name,docName:doc.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getLayerList(){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layers=[];function getLayers(layerSet,indent){for(var i=0;i<layerSet.layers.length;i++){var layer=layerSet.layers[i];var layerInfo={name:layer.name,kind:layer.kind.toString(),visible:layer.visible,isSmartObject:layer.typename==="Layer"&&layer.bounds,indent:indent};layers.push(layerInfo);if(layer.typename==="LayerSet"){getLayers(layer,indent+1)}}}getLayers(doc,0);return JSON.stringify({success:true,layerCount:layers.length,layers:layers})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}
