// SubliStudio CEP - Complete ExtendScript Host
// This file contains ALL functions from all modules
#target photoshop

// ============================================================================
// DOCUMENT OPERATIONS
// ============================================================================

function openDocument(path){try{var file=new File(path);if(!file.exists){return JSON.stringify({success:false,error:"File not found: "+path})}var doc=app.open(file);return JSON.stringify({success:true,message:"Document opened",docName:doc.name,docPath:doc.fullName.fsName,width:doc.width.as("px"),height:doc.height.as("px"),resolution:doc.resolution.as("px/in"),colorMode:doc.mode.toString(),layerCount:doc.layers.length})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function closeDocument(save){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;if(save){doc.save();doc.close();return JSON.stringify({success:true,message:"Document saved and closed"})}else{doc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:true,message:"Document closed without saving"})}}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function createDocument(widthCm,heightCm,dpi,name,colorMode){try{var width=UnitValue(widthCm,"cm");var height=UnitValue(heightCm,"cm");var resolution=UnitValue(dpi,"px/in");var mode=NewDocumentMode.RGB;if(colorMode==="CMYK")mode=NewDocumentMode.CMYK;else if(colorMode==="Grayscale")mode=NewDocumentMode.GRAYSCALE;else if(colorMode==="Bitmap")mode=NewDocumentMode.BITMAP;else if(colorMode==="Lab")mode=NewDocumentMode.LAB;var doc=app.documents.add(width,height,resolution,name,mode,DocumentFill.TRANSPARENT);return JSON.stringify({success:true,message:"Document created",docName:doc.name,width:doc.width.as("px"),height:doc.height.as("px"),resolution:doc.resolution.as("px/in"),colorMode:doc.mode.toString()})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getDocumentInfo(){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;return JSON.stringify({success:true,docName:doc.name,docPath:doc.fullName?doc.fullName.fsName:"",width:doc.width.as("px"),height:doc.height.as("px"),widthCm:doc.width.as("cm"),heightCm:doc.height.as("cm"),resolution:doc.resolution.as("px/in"),colorMode:doc.mode.toString(),layerCount:doc.layers.length,hasBackground:doc.backgroundLayer!==null,bitsPerChannel:doc.bitsPerChannel})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function saveDocument(path,format){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;if(!path){doc.save();return JSON.stringify({success:true,message:"Document saved"})}var file=new File(path);var saveOptions;if(format==="PSD"){saveOptions=new PhotoshopSaveOptions();saveOptions.alphaChannels=true;saveOptions.layers=true;saveOptions.embedColorProfile=true}else if(format==="JPEG"){saveOptions=new JPEGSaveOptions();saveOptions.quality=12;saveOptions.embedColorProfile=true}else if(format==="PNG"){saveOptions=new PNGSaveOptions();saveOptions.compression=1}else if(format==="TIFF"){saveOptions=new TiffSaveOptions();saveOptions.LZW=true}else if(format==="PDF"){saveOptions=new PDFSaveOptions()}else{return JSON.stringify({success:false,error:"Unknown format: "+format})}doc.saveAs(file,saveOptions,true,Extension.LOWERCASE);return JSON.stringify({success:true,message:"Document saved as "+format,path:path})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

// ============================================================================
// LAYER OPERATIONS
// ============================================================================

function getLayerList(){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layers=[];function getLayers(layerSet,indent){for(var i=0;i<layerSet.layers.length;i++){var layer=layerSet.layers[i];var layerInfo={name:layer.name,kind:layer.kind.toString(),visible:layer.visible,opacity:layer.opacity,isSmartObject:(layer.typename==="ArtLayer"&&layer.bounds),indent:indent,bounds:{left:layer.bounds[0].as("px"),top:layer.bounds[1].as("px"),right:layer.bounds[2].as("px"),bottom:layer.bounds[3].as("px")}};layers.push(layerInfo);if(layer.typename==="LayerSet"){getLayers(layer,indent+1)}}}getLayers(doc,0);return JSON.stringify({success:true,layerCount:layers.length,layers:layers})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getLayersByPattern(pattern){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var matchingLayers=[];var regex=new RegExp("^"+pattern.replace("*",".*")+"$","i");function findMatchingLayers(layerSet){for(var i=0;i<layerSet.layers.length;i++){var layer=layerSet.layers[i];if(regex.test(layer.name)){matchingLayers.push({name:layer.name,index:i,kind:layer.kind.toString(),visible:layer.visible,bounds:{left:layer.bounds[0].as("px"),top:layer.bounds[1].as("px"),right:layer.bounds[2].as("px"),bottom:layer.bounds[3].as("px"),width:(layer.bounds[2].as("px")-layer.bounds[0].as("px")),height:(layer.bounds[3].as("px")-layer.bounds[1].as("px"))}})}if(layer.typename==="LayerSet"){findMatchingLayers(layer)}}}findMatchingLayers(doc);return JSON.stringify({success:true,pattern:pattern,count:matchingLayers.length,layers:matchingLayers})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getLayerBounds(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}return JSON.stringify({success:true,layerName:layerName,bounds:{left:layer.bounds[0].as("px"),top:layer.bounds[1].as("px"),right:layer.bounds[2].as("px"),bottom:layer.bounds[3].as("px"),width:(layer.bounds[2].as("px")-layer.bounds[0].as("px")),height:(layer.bounds[3].as("px")-layer.bounds[1].as("px"))}})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function duplicateLayer(layerName,newName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);var newLayer=layer.duplicate();if(newName){newLayer.name=newName}return JSON.stringify({success:true,message:"Layer duplicated",newName:newLayer.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function moveLayer(layerName,x,y){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);var bounds=layer.bounds;var deltaX=UnitValue(x,"px")-bounds[0];var deltaY=UnitValue(y,"px")-bounds[1];layer.translate(deltaX,deltaY);return JSON.stringify({success:true,message:"Layer moved",x:x,y:y})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function resizeLayer(layerName,scalePercent){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.resize(scalePercent,scalePercent);return JSON.stringify({success:true,message:"Layer resized",scalePercent:scalePercent})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function rotateLayer(layerName,degrees){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.rotate(degrees);return JSON.stringify({success:true,message:"Layer rotated",degrees:degrees})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function deleteLayer(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.remove();return JSON.stringify({success:true,message:"Layer deleted"})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function setLayerVisibility(layerName,visible){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.visible=visible;return JSON.stringify({success:true,message:"Layer visibility set",visible:visible})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function setLayerOpacity(layerName,opacity){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.opacity=opacity;return JSON.stringify({success:true,message:"Layer opacity set",opacity:opacity})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

// ============================================================================
// SMART OBJECT OPERATIONS (FIXED with Action Manager)
// ============================================================================

function placeImageInSmartObject(layerName,imagePath){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(layer.kind!=LayerKind.SMARTOBJECT){return JSON.stringify({success:false,error:"Layer is not a smart object: "+layerName})}var file=new File(imagePath);if(!file.exists){return JSON.stringify({success:false,error:"Image file not found: "+imagePath})}doc.activeLayer=layer;var idplacedLayer=stringIDToTypeID("placedLayer");var desc=new ActionDescriptor();var idnull=charIDToTypeID("null");var ref=new ActionReference();var idlayer=charIDToTypeID("Lyr ");var idordinal=charIDToTypeID("Ordn");var idtarget=charIDToTypeID("Trgt");ref.putEnumerated(idlayer,idordinal,idtarget);desc.putReference(idnull,ref);var idID=charIDToTypeID("ID  ");desc.putInteger(idID,layer.id);var idfile=charIDToTypeID("file");desc.putPath(idfile,file);executeAction(idplacedLayer,desc,DialogModes.NO);return JSON.stringify({success:true,message:"Smart object contents replaced",layerName:layerName,imagePath:imagePath})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function placeImageAsNewLayer(imagePath,x,y,scale){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var file=new File(imagePath);if(!file.exists){return JSON.stringify({success:false,error:"Image file not found: "+imagePath})}var idplacedLayer=stringIDToTypeID("placedLayer");var desc=new ActionDescriptor();var idnull=charIDToTypeID("null");desc.putPath(idnull,file);executeAction(idplacedLayer,desc,DialogModes.NO);var placedLayer=doc.activeLayer;if(x!==undefined&&y!==undefined){var bounds=placedLayer.bounds;var deltaX=UnitValue(x,"px")-bounds[0];var deltaY=UnitValue(y,"px")-bounds[1];placedLayer.translate(deltaX,deltaY)}if(scale&&scale!==100){placedLayer.resize(scale,scale)}return JSON.stringify({success:true,message:"Image placed as new layer",layerName:placedLayer.name,x:x,y:y,scale:scale})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function isSmartObject(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}var isSO=(layer.kind==LayerKind.SMARTOBJECT);return JSON.stringify({success:true,layerName:layerName,isSmartObject:isSO})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getSmartObjectContents(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(layer.kind!=LayerKind.SMARTOBJECT){return JSON.stringify({success:false,error:"Layer is not a smart object"})}var ref=new ActionReference();var idproperty=charIDToTypeID("property");var idnull=charIDToTypeID("null");var idlayer=charIDToTypeID("Lyr ");var idordinal=charIDToTypeID("Ordn");var idtarget=charIDToTypeID("Trgt");ref.putEnumerated(idlayer,idordinal,idtarget);var idlinkedLayerFile=stringIDToTypeID("linkedLayerFile");ref.putProperty(idproperty,idlinkedLayerFile);var desc=executeActionGet(ref);var filePath="";try{var linkedFile=desc.getPath(idlinkedLayerFile);filePath=linkedFile.fsName}catch(e){filePath="embedded"}return JSON.stringify({success:true,layerName:layerName,filePath:filePath,isLinked:filePath!=="embedded"})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function convertToSmartObject(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var idnewPlacedLayer=stringIDToTypeID("newPlacedLayer");executeAction(idnewPlacedLayer,undefined,DialogModes.NO);return JSON.stringify({success:true,message:"Layer converted to smart object",layerName:layer.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function exportSmartObjectContents(layerName,outputPath){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(layer.kind!=LayerKind.SMARTOBJECT){return JSON.stringify({success:false,error:"Layer is not a smart object"})}doc.activeLayer=layer;var file=new File(outputPath);var idplacedLayer=stringIDToTypeID("placedLayer");var desc=new ActionDescriptor();var idnull=charIDToTypeID("null");var ref=new ActionReference();var idlayer=charIDToTypeID("Lyr ");var idordinal=charIDToTypeID("Ordn");var idtarget=charIDToTypeID("Trgt");ref.putEnumerated(idlayer,idordinal,idtarget);desc.putReference(idnull,ref);var idID=charIDToTypeID("ID  ");desc.putInteger(idID,layer.id);var idfile=charIDToTypeID("file");desc.putPath(idfile,file);executeAction(idplacedLayer,desc,DialogModes.NO);return JSON.stringify({success:true,message:"Smart object contents exported",outputPath:outputPath})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

// ============================================================================
// EFFECTS & FILTERS
// ============================================================================

function applyCircularMask(layerName,x,y,radius){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var bounds=[UnitValue(x-radius,"px"),UnitValue(y-radius,"px"),UnitValue(x+radius,"px"),UnitValue(y+radius,"px")];doc.selection.select(bounds,SelectionType.REPLACE,0,false);doc.selection.invert();doc.selection.clear();doc.selection.deselect();return JSON.stringify({success:true,message:"Circular mask applied",layerName:layerName,x:x,y:y,radius:radius})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function applyGaussianBlur(layerName,radius){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var idGaussianBlur=stringIDToTypeID("Gaussian Blur");var desc=new ActionDescriptor();var idRadius=charIDToTypeID("Rad ");desc.putUnitDouble(idRadius,charIDToTypeID("#Pxl"),radius);executeAction(idGaussianBlur,desc,DialogModes.NO);return JSON.stringify({success:true,message:"Gaussian blur applied",layerName:layerName,radius:radius})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function applyLayerStyle(layerName,styleType,params){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(styleType==="dropShadow"){layer.effect.dropShadow=true;if(params&&params.distance)layer.effects.dropShadow.distance=params.distance;if(params&&params.size)layer.effects.dropShadow.size=params.size;if(params&&params.opacity)layer.effects.dropShadow.opacity=params.opacity}else if(styleType==="bevel"){layer.effect.bevelEmboss=true;if(params&&params.size)layer.effects.bevelEmboss.size=params.size;if(params&&params.depth)layer.effects.bevelEmboss.depth=params.depth}else if(styleType==="outerGlow"){layer.effect.outerGlow=true;if(params&&params.size)layer.effects.outerGlow.size=params.size;if(params&&params.opacity)layer.effects.outerGlow.opacity=params.opacity}return JSON.stringify({success:true,message:"Layer style applied",layerName:layerName,styleType:styleType})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function mirrorLayer(layerName,axis){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var idflip=stringIDToTypeID("flip");var desc=new ActionDescriptor();var idHrzn=charIDToTypeID("Hrzn");var idVrtc=charIDToTypeID("Vrtc");if(axis==="horizontal"){desc.putBoolean(idHrzn,true)}else if(axis==="vertical"){desc.putBoolean(idVrtc,true)}else{return JSON.stringify({success:false,error:"Invalid axis: "+axis})}executeAction(idflip,desc,DialogModes.NO);return JSON.stringify({success:true,message:"Layer mirrored",layerName:layerName,axis:axis})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function applyColorOverlay(layerName,r,g,b,opacity){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}layer.effect.colorOverlay=true;layer.effects.colorOverlay.color.rgb.red=r;layer.effects.colorOverlay.color.rgb.green=g;layer.effects.colorOverlay.color.rgb.blue=b;layer.effects.colorOverlay.opacity=opacity;return JSON.stringify({success:true,message:"Color overlay applied",layerName:layerName,color:{r:r,g:g,b:b},opacity:opacity})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

// ============================================================================
// EXPORT OPERATIONS (FIXED)
// ============================================================================

function flattenAndExport(format,path,options){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var file=new File(path);var dupDoc=doc.duplicate();dupDoc.flatten();var saveOptions;if(format==="PNG"){saveOptions=new PNGSaveOptions();saveOptions.compression=(options&&options.compression)?options.compression:1}else if(format==="JPEG"){saveOptions=new JPEGSaveOptions();saveOptions.quality=(options&&options.quality)?options.quality:12;saveOptions.embedColorProfile=true}else if(format==="TIFF"){saveOptions=new TiffSaveOptions();saveOptions.LZW=(options&&options.compression)?options.compression:true}else if(format==="PDF"){saveOptions=new PDFSaveOptions()}else{dupDoc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:false,error:"Unknown format: "+format})}dupDoc.saveAs(file,saveOptions,true,Extension.LOWERCASE);dupDoc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:true,message:"Document flattened and exported",format:format,path:path,width:doc.width.as("px"),height:doc.height.as("px")})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function exportLayer(layerName,path,format){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}var originalVisibility=[];for(var i=0;i<doc.layers.length;i++){originalVisibility.push(doc.layers[i].visible);doc.layers[i].visible=false}layer.visible=true;var file=new File(path);var saveOptions;if(format==="PNG"){saveOptions=new PNGSaveOptions()}else if(format==="JPEG"){saveOptions=new JPEGSaveOptions();saveOptions.quality=12}else if(format==="TIFF"){saveOptions=new TiffSaveOptions();saveOptions.LZW=true}else{saveOptions=new PNGSaveOptions()}doc.saveAs(file,saveOptions,true,Extension.LOWERCASE);for(var i=0;i<doc.layers.length;i++){doc.layers[i].visible=originalVisibility[i]}return JSON.stringify({success:true,message:"Layer exported",layerName:layerName,path:path,format:format})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function exportPreview(path,maxWidth){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var currentWidth=doc.width.as("px");var currentHeight=doc.height.as("px");var dupDoc=doc.duplicate();dupDoc.flatten();if(currentWidth>maxWidth){var scale=(maxWidth/currentWidth)*100;dupDoc.resizeImage(UnitValue(scale,"%"),null,null,ResampleMethod.BICUBIC)}var file=new File(path);var saveOptions=new JPEGSaveOptions();saveOptions.quality=8;saveOptions.embedColorProfile=false;dupDoc.saveAs(file,saveOptions,true,Extension.LOWERCASE);dupDoc.close(SaveOptions.DONOTSAVECHANGES);return JSON.stringify({success:true,message:"Preview exported",path:path,width:dupDoc.width.as("px"),height:dupDoc.height.as("px")})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function createPrintSheet(widthCm,heightCm,dpi,designs){try{var sheet=app.documents.add(UnitValue(widthCm,"cm"),UnitValue(heightCm,"cm"),UnitValue(dpi,"px/in"),"Print Sheet",NewDocumentMode.RGB,DocumentFill.WHITE);for(var i=0;i<designs.length;i++){var design=designs[i];var file=new File(design.path);if(file.exists){var idplacedLayer=stringIDToTypeID("placedLayer");var desc=new ActionDescriptor();var idnull=charIDToTypeID("null");desc.putPath(idnull,file);executeAction(idplacedLayer,desc,DialogModes.NO);var placedLayer=sheet.activeLayer;var bounds=placedLayer.bounds;var deltaX=UnitValue(design.x,"px")-bounds[0];var deltaY=UnitValue(design.y,"px")-bounds[1];placedLayer.translate(deltaX,deltaY);if(design.mirror){sheet.activeLayer=placedLayer;var idflip=stringIDToTypeID("flip");var descFlip=new ActionDescriptor();var idHrzn=charIDToTypeID("Hrzn");descFlip.putBoolean(idHrzn,true);executeAction(idflip,descFlip,DialogModes.NO)}}}return JSON.stringify({success:true,message:"Print sheet created",designCount:designs.length,docName:sheet.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

// ============================================================================
// PHASE 0 LEGACY FUNCTIONS (backward compatibility)
// ============================================================================

function getPhotoshopInfo(){try{var info={version:app.version,appName:app.name,hasDoc:false,docName:"",docWidth:0,docHeight:0,docResolution:0,colorMode:""};if(app.documents.length>0){var doc=app.activeDocument;info.hasDoc=true;info.docName=doc.name;info.docWidth=doc.width.as("cm");info.docHeight=doc.height.as("cm");info.docResolution=doc.resolution.as("px/in");switch(doc.mode){case DocumentMode.RGB:info.colorMode="RGB";break;case DocumentMode.CMYK:info.colorMode="CMYK";break;case DocumentMode.GRAYSCALE:info.colorMode="Grayscale";break;case DocumentMode.BITMAP:info.colorMode="Bitmap";break;case DocumentMode.LAB:info.colorMode="Lab";break;default:info.colorMode="Unknown"}}return JSON.stringify(info)}catch(e){return JSON.stringify({error:true,message:e.toString()})}}

function pingPhotoshop(){try{return JSON.stringify({success:true,version:app.version,message:"Photoshop is responding"})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function createTestDocument(){try{var doc=app.documents.add(UnitValue(21,"cm"),UnitValue(29.7,"cm"),300,"SubliStudio Test",NewDocumentMode.RGB);return JSON.stringify({success:true,message:"Document created: "+doc.name,docName:doc.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function log(message){$.writeln("[SubliStudio] "+message)}
