// SubliStudio CEP - Layer Operations
#target photoshop

function getLayerList(){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layers=[];function getLayers(layerSet,indent){for(var i=0;i<layerSet.layers.length;i++){var layer=layerSet.layers[i];var layerInfo={name:layer.name,kind:layer.kind.toString(),visible:layer.visible,opacity:layer.opacity,isSmartObject:(layer.typename==="ArtLayer"&&layer.bounds),indent:indent,bounds:{left:layer.bounds[0].as("px"),top:layer.bounds[1].as("px"),right:layer.bounds[2].as("px"),bottom:layer.bounds[3].as("px")}};layers.push(layerInfo);if(layer.typename==="LayerSet"){getLayers(layer,indent+1)}}}getLayers(doc,0);return JSON.stringify({success:true,layerCount:layers.length,layers:layers})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getLayersByPattern(pattern){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var matchingLayers=[];var regex=new RegExp("^"+pattern.replace("*",".*")+"$","i");function findMatchingLayers(layerSet){for(var i=0;i<layerSet.layers.length;i++){var layer=layerSet.layers[i];if(regex.test(layer.name)){matchingLayers.push({name:layer.name,index:i,kind:layer.kind.toString(),visible:layer.visible,bounds:{left:layer.bounds[0].as("px"),top:layer.bounds[1].as("px"),right:layer.bounds[2].as("px"),bottom:layer.bounds[3].as("px"),width:(layer.bounds[2].as("px")-layer.bounds[0].as("px")),height:(layer.bounds[3].as("px")-layer.bounds[1].as("px"))}})}if(layer.typename==="LayerSet"){findMatchingLayers(layer)}}}findMatchingLayers(doc);return JSON.stringify({success:true,pattern:pattern,count:matchingLayers.length,layers:matchingLayers})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getLayerBounds(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}return JSON.stringify({success:true,layerName:layerName,bounds:{left:layer.bounds[0].as("px"),top:layer.bounds[1].as("px"),right:layer.bounds[2].as("px"),bottom:layer.bounds[3].as("px"),width:(layer.bounds[2].as("px")-layer.bounds[0].as("px")),height:(layer.bounds[3].as("px")-layer.bounds[1].as("px"))}})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function duplicateLayer(layerName,newName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);var newLayer=layer.duplicate();if(newName){newLayer.name=newName}return JSON.stringify({success:true,message:"Layer duplicated",newName:newLayer.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function moveLayer(layerName,x,y){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);var bounds=layer.bounds;var deltaX=UnitValue(x,"px")-bounds[0];var deltaY=UnitValue(y,"px")-bounds[1];layer.translate(deltaX,deltaY);return JSON.stringify({success:true,message:"Layer moved",x:x,y:y})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function resizeLayer(layerName,scalePercent){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);var bounds=layer.bounds;var width=bounds[2].as("px")-bounds[0].as("px");var height=bounds[3].as("px")-bounds[1].as("px");var newWidth=UnitValue(width*(scalePercent/100),"px");var newHeight=UnitValue(height*(scalePercent/100),"px");layer.resize(newWidth.as("px"),newHeight.as("px"));return JSON.stringify({success:true,message:"Layer resized",scalePercent:scalePercent})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function rotateLayer(layerName,degrees){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.rotate(degrees);return JSON.stringify({success:true,message:"Layer rotated",degrees:degrees})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function deleteLayer(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.remove();return JSON.stringify({success:true,message:"Layer deleted"})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function setLayerVisibility(layerName,visible){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.visible=visible;return JSON.stringify({success:true,message:"Layer visibility set",visible:visible})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function setLayerOpacity(layerName,opacity){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);layer.opacity=opacity;return JSON.stringify({success:true,message:"Layer opacity set",opacity:opacity})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}
