// SubliStudio CEP - Smart Object Operations
#target photoshop

function placeImageInSmartObject(layerName,imagePath){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(layer.kind!=LayerKind.SMARTOBJECT){return JSON.stringify({success:false,error:"Layer is not a smart object: "+layerName})}var smartObject=layer.smartObject;var file=new File(imagePath);if(!file.exists){return JSON.stringify({success:false,error:"Image file not found: "+imagePath})}smartObject.replaceContents(file);return JSON.stringify({success:true,message:"Smart object contents replaced",layerName:layerName,imagePath:imagePath})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function placeImageAsNewLayer(imagePath,x,y,scale){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var file=new File(imagePath);if(!file.exists){return JSON.stringify({success:false,error:"Image file not found: "+imagePath})}var placedLayer=doc.placedLayer(file);var bounds=placedLayer.bounds;var deltaX=UnitValue(x,"px")-bounds[0];var deltaY=UnitValue(y,"px")-bounds[1];placedLayer.translate(deltaX,deltaY);if(scale&&scale!==100){var width=bounds[2].as("px")-bounds[0].as("px");var height=bounds[3].as("px")-bounds[1].as("px");var newWidth=UnitValue(width*(scale/100),"px");var newHeight=UnitValue(height*(scale/100),"px");placedLayer.resize(newWidth.as("px"),newHeight.as("px"))}return JSON.stringify({success:true,message:"Image placed as new layer",layerName:placedLayer.name,x:x,y:y,scale:scale})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function isSmartObject(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}var isSO=(layer.kind==LayerKind.SMARTOBJECT);return JSON.stringify({success:true,layerName:layerName,isSmartObject:isSO})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function getSmartObjectContents(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(layer.kind!=LayerKind.SMARTOBJECT){return JSON.stringify({success:false,error:"Layer is not a smart object"})}var smartObject=layer.smartObject;var file=smartObject.linkedFile;return JSON.stringify({success:true,layerName:layerName,filePath:file?file.fsName:"",isLinked:smartObject.linkedFile!==null})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function convertToSmartObject(layerName){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}doc.activeLayer=layer;var idnewPlacedLayer=stringIDToTypeID("newPlacedLayer");executeAction(idnewPlacedLayer,undefined,DialogModes.NO);return JSON.stringify({success:true,message:"Layer converted to smart object",layerName:layer.name})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}

function exportSmartObjectContents(layerName,outputPath){try{if(app.documents.length===0){return JSON.stringify({success:false,error:"No document open"})}var doc=app.activeDocument;var layer=doc.layers.getByName(layerName);if(!layer){return JSON.stringify({success:false,error:"Layer not found: "+layerName})}if(layer.kind!=LayerKind.SMARTOBJECT){return JSON.stringify({success:false,error:"Layer is not a smart object"})}var smartObject=layer.smartObject;var file=new File(outputPath);smartObject.exportContents(file);return JSON.stringify({success:true,message:"Smart object contents exported",outputPath:outputPath})}catch(e){return JSON.stringify({success:false,error:e.toString()})}}
